apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    version: v1
  name: backend
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    version: v1
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      serviceAccountName: backend
      containers:
        - env:
            - name: SERVICE_OWNER
              value: "oli"
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:8080"
            - name: "SERVER_TYPE"
              value: "http"
            - name: "NAME"
              value: "backend-cluster1"
            - name: "MESSAGE"
              value: "Hello from backend"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: rinormaloku/happy-service:latest
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          securityContext:
            privileged: false
