apiVersion: apps/v1
kind: Deployment
metadata:
  name: extauth-grpcservice
  namespace: bookinfo-backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-extauth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpc-extauth
    spec:
      containers:
      - image: rinormaloku/passthrough-grpc-service-example:latest
        imagePullPolicy: Always
        name: grpc-extauth
        ports:
        - containerPort: 9001
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-extauth
  name: example-grpc-auth-service
  namespace: bookinfo-backends
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: grpc-extauth
  sessionAffinity: None
  type: ClusterIP
---